# Generated by Django 4.1.3 on 2023-05-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2p_project_names",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
