# Generated by Django 4.1.3 on 2023-05-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_b2p_project_names_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2p_project_names",
            name="project_2",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="b2p_sites",
            name="site",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
