# Generated by Django 4.1.3 on 2023-11-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_b2p_project_names_project_2_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="b2p_project_names", new_name="b2p_project_name",
        ),
        migrations.RenameModel(old_name="b2p_sites", new_name="b2p_site",),
    ]
