# Generated by Django 4.1.3 on 2023-11-14 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_b2p_project_names_b2p_project_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="b2p_program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="b2p_reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[("PPM", "PPM"), ("Hourly", "Hourly")], max_length=50
                    ),
                ),
                ("effectived_date", models.DateField(default=datetime.date.today)),
                ("b2p_target", models.FloatField(blank=True, null=True)),
                ("aht_cap", models.FloatField(blank=True, null=True)),
                ("ob_cap", models.FloatField(blank=True, null=True)),
                ("fte_cap", models.FloatField(blank=True, null=True)),
                ("fte_capping", models.FloatField(blank=True, null=True)),
                ("shrink", models.FloatField(blank=True, null=True)),
                ("sme_shrink", models.FloatField(blank=True, null=True)),
                ("flex_sme_ratio", models.FloatField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.b2p_program",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.b2p_site"
                    ),
                ),
            ],
        ),
    ]
