# Generated by Django 4.1.3 on 2023-11-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_b2p_program_b2p_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2p_program",
            name="program",
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
