# Generated by Django 4.2.7 on 2023-12-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_b2p_flex_agents_program_b2p_flex_nesting_agents_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2p_project_name',
            old_name='effectived_date',
            new_name='effective_date',
        ),
        migrations.RenameField(
            model_name='b2p_reference',
            old_name='effectived_date',
            new_name='effective_date',
        ),
        migrations.RemoveField(
            model_name='b2p_project_name',
            name='project_2',
        ),
        migrations.AddField(
            model_name='b2p_project_name',
            name='true_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.b2p_program'),
        ),
    ]
