# Generated by Django 4.2.7 on 2023-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_effectived_date_b2p_project_name_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='b2p_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(db_index=True, max_length=300)),
            ],
        ),
    ]
