# Generated by Django 4.2.7 on 2023-12-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_b2p_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2p_flex_nesting_agents_program',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='b2p_flex_sme_ratio_program',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='b2p_rates_program',
            name='assignment',
        ),
    ]
